version: '3.5'
services:
  customer-payment-mysql:
    image: 'mysql:8.4.3'
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=customerpaymentdb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./.data/customer-payment-mysql:/var/lib/mysql
      - ./customer-payment-mysql:/docker-entrypoint-initdb.d/
  inventory-mysql:
    image: 'mysql:8.4.3'
    ports:
      - "3307:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=inventorydb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./.data/inventory-mysql:/var/lib/mysql
      - ./inventory-mysql:/docker-entrypoint-initdb.d/
  order-mysql:
    image: 'mysql:8.4.3'
    ports:
      - "3308:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=orderdb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./.data/order-mysql:/var/lib/mysql
      - ./order-mysql:/docker-entrypoint-initdb.d/
  shipping-mysql:
    image: 'mysql:8.4.3'
    ports:
      - "3309:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=shippingdb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./.data/shipping-mysql:/var/lib/mysql
      - ./shipping-mysql:/docker-entrypoint-initdb.d/
  kafka:
    image: bitnami/kafka:4.0.0
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=kafka-kraft-cluster
    volumes:
      - ./.data/kafka:/bitnami/kafka
  dead-letter-kafka:
    image: bitnami/kafka:4.0.0
    ports:
      - "9095:9095"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@dead-letter-kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://dead-letter-kafka:9092,EXTERNAL://localhost:9095
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=dead-letter-kafka-kraft-cluster
    volumes:
      - ./.data/dead-letter-kafka:/bitnami/kafka
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8089:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_1_NAME=dead-letter-kafka
      - KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS=dead-letter-kafka:9092
    depends_on:
      - kafka
      - dead-letter-kafka